name: Test
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - package.json
      - src/**/*
      - .github/workflows/**

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Nodes
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Test
        run: npm run build
